auto/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static

from auto.views import *
from autolux import settings

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('products/<slug:item_name>', Products.as_view(), name='products'),
    path('<slug:category>/<slug:itemslug>', ProductDescription.as_view(), name='single'),
    path('about', About.as_view(), name='about'),
    path('contact', Contact.as_view(), name='contact'),
    path('place_order', PlaceOrder.as_view(), name='place_order'),
    path('car_information', CarInformation.as_view(), name='car_information'),
    path('login', Login.as_view(), name='login'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

autolux/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    path('', include('auto.urls')),
    path('admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auto/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import BaseUserManager
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
import json
from autoslug import AutoSlugField

Category_CHOICES = (
    ('Interior', 'INTERIOR'),
    ('Exterior', 'EXTERIOR'),
    ('Mats', 'MATS'),
    ('Detailing', 'DETAILING'),
    ('Leds', 'LEDS'),
    ('Suvs', 'SUVS'),
    ('Utilites', 'UTILITES'),
    ('Others', 'OTHERS'),
)


class ProductColors(models.Model):
    color = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color


class Product(models.Model):
    product_title = models.CharField(max_length=255)
    product_slug = AutoSlugField(null=True, default=None, unique=True, populate_from='product_title')
    product_category = models.CharField(max_length=9, choices=Category_CHOICES, default='EPIC')
    product_image_front = models.ImageField(upload_to='images')
    product_image_front_alt = models.CharField(max_length=200, blank=True, null=True)
    front_image_thumbnail = ImageSpecField(source='product_image_front',
                                      processors=[ResizeToFill(200, 150)],
                                      format='JPEG',
                                      options={'quality': 50})
    product_image_back = models.ImageField(upload_to='images')
    product_image_back_alt = models.CharField(max_length=200, blank=True, null=True)
    back_image_thumbnail = ImageSpecField(source='product_image_back',
                                           processors=[ResizeToFill(200, 150)],
                                           format='JPEG',
                                           options={'quality': 50})
    product_price = models.FloatField(null=False,default=0)
    product_discounted_price = models.FloatField(blank=True, null=True)
    product_colors = models.ManyToManyField(ProductColors,null=True, blank=True)
    product_meta_description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_title


class ProductSpecification(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_related_name')
    product_description = models.CharField(max_length=200)
    product_information = models.CharField(max_length=200)
    product_review = models.CharField(max_length=200)
    first_image_alt = models.CharField(max_length=200, blank=True, null=True)
    first_image = models.ImageField(upload_to='images')
    first_image_thumbnail = ImageSpecField(source='first_image',
                                          processors=[ResizeToFill(200, 150)],
                                          format='JPEG',
                                          options={'quality': 50})
    second_image_alt = models.CharField(max_length=200, blank=True, null=True)
    second_image = models.ImageField(upload_to='images')
    second_image_thumbnail = ImageSpecField(source='second_image',
                                           processors=[ResizeToFill(200, 150)],
                                           format='JPEG',
                                           options={'quality': 50})
    third_image_alt = models.CharField(max_length=200, blank=True, null=True)
    third_image = models.ImageField(upload_to='images')
    third_image_thumbnail = ImageSpecField(source='third_image',
                                           processors=[ResizeToFill(200, 150)],
                                           format='JPEG',
                                           options={'quality': 50})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_id.product_title


class CarCompany(models.Model):
    # product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cars_related_name')
    car_make = models.CharField(max_length=30)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.car_make


class CarModel(models.Model):
    company = models.ForeignKey(CarCompany, on_delete=models.CASCADE, related_name='company_related_name')
    car_model = models.CharField(max_length=30)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.car_model


class CarYear(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cars_related_name',blank=True,null=True)
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, related_name='model_related_name')
    car_year = models.CharField(max_length=30)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.model.car_model + " " + self.car_year


class UserWithoutAccount(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Contact Number is not valid")
    contact_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    address = models.CharField(max_length=500)
    email = models.EmailField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Online User Order'
        verbose_name_plural = 'Online User Order'

    def __str__(self):
        return self.first_name + " " + self.last_name


class Order(models.Model):
    user = models.ForeignKey(UserWithoutAccount, on_delete=models.CASCADE, related_name='users_without_account')
    item_id = models.CharField(max_length=20)
    item_name = models.CharField(max_length=200)
    item_quantity = models.CharField(max_length=20, default=1)
    item_price = models.CharField(max_length=20)
    total_price = models.CharField(max_length=20, default=0)
    payment_status = models.BooleanField(default=False)
    charge_id = models.CharField(max_length=234, default="None")
    colors = models.CharField(max_length=500, null=True, blank=True)
    order_number = models.CharField(blank=True, null=True, max_length=6)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item_name

    def set_colors(self, colors):
        self.colors = json.dumps(colors)

    def get_colors(self):
        return json.loads(self.colors)


class SliderImage(models.Model):
    main_slider_image_alt = models.CharField(max_length=200, blank=True, null=True)
    main_slider_image = models.ImageField(upload_to='images')
    slider_image_thumbnail = ImageSpecField(source='main_slider_image',
                                           processors=[ResizeToFill(1400, 600)],
                                           format='JPEG',
                                           options={'quality': 50})

    def __str__(self):
        return "Sliding-image-" + str(self.id)


class OrderPageBackground(models.Model):
    background_image = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='Order Page Background')
    mobile_image = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='Order Page Mobile Background')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = 'created_at'

    def __str__(self):
        return str(self.background_image)


class HomePageCategoriesImages(models.Model):
    led_lights_alt = models.CharField(max_length=200, blank=True, null=True)
    led_lights = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='LED LIGHTS')

    interior_alt = models.CharField(max_length=200, blank=True, null=True)
    interior = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='INTERIOR')

    suv_items_alt = models.CharField(max_length=200, blank=True, null=True)
    suv_items = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='SUV ITEMS 4X4')

    exterior_alt = models.CharField(max_length=200, blank=True, null=True)
    exterior = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='EXTERIOR')

    car_detailing_alt = models.CharField(max_length=200, blank=True, null=True)
    car_detailing = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='CAR DETAILING')

    outdoor_utilities_alt = models.CharField(max_length=200, blank=True, null=True)
    outdoor_utilities = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='OUTDOOR UTILITIES')

    shop_now = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='SHOP NOW')
    shop_now_mobile = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='SHOP NOW MOBILE')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = 'created_at'


class CategoryWiseImageBackground(models.Model):
    interior_alt = models.CharField(max_length=200, blank=True, null=True)
    interior = models.ImageField(upload_to="images", blank=True, null=True, verbose_name='INTERIOR')

auto/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from auto.models import UserWithoutAccount, Order


class SignUpForm(UserCreationForm):
    full_Name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=254, required=True)
    address = forms.CharField(max_length=30, required=True,)

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = get_user_model()
        fields = ('full_Name', 'email', 'password1', 'password2', 'address')


class SignInForm(forms.Form):
    email = forms.EmailField(max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)


class UserOrderForm(forms.ModelForm):
    class Meta:
        model = UserWithoutAccount
        fields = ['first_name', 'last_name','email','contact_number','address']


class SimpleOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'item_id', 'item_name', 'item_price', 'payment_status', 'charge_id']

auto/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="16x16">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>
    <!-- //for bootstrap working -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
{% endblock %}
{% block content %}

    <div class="contact-us-image">
        <img style="width: 100%" src="{% static 'images/about_us.jpg' %}">
        <div class="container myclass">
        <div class="col-md-offset-5 col-md-3">
            <h3 class="contact-us-title-setting" style="color: ghostwhite;">About<span> Us</span></h3>
        </div>
{#        <h3 class="contact-us-title-setting">About<span> Us</span></h3>#}
        <!--/w3_short-->
             <div class="services-breadcrumb">
                <div class="agile_inner_breadcrumb">

                   <ul class="w3_short">
                        <li><a href="{% url 'index' %}">Home</a><i>|</i></li>
                        <li>About</li>
                    </ul>
                 </div>
            </div>
	   <!--//w3_short-->
	    </div>
    </div>

<!-- /banner_bottom_agile_info -->
    <div class="banner_bottom_agile_info">
	    <div class="container">
			<div class="agile_ab_w3ls_info">
				<div class="col-md-12" align="center">
				   	<img src="{% static 'images/Auto Lux for about us.png' %}" alt=" " class="img-responsive" />
				</div>
                 <div class="col-md-offset-2 col-md-8 about-us-content" align="center">
                     <p>AutoLux.pk is dedicated to provide unique and rare car accessories that are either
                        not available in Pakistan or are extremely rare. We aim to import such automotive
                        products and provide them at reasonable and competitive prices. All of our
                        products and car accessories are self-imported by taking the market dynamics into
                        account. However, we also arrange one-off shipments on pre-order for interested
                        customers.
                     </p>
                 </div>
				  <div class="clearfix"></div>
			</div>
		 </div>
    </div>
	<!-- team -->
{% endblock %}

auto/templates/add-to-cart-partial.html
<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
    <form action="#" method="post" id="add_to_cart{{ item.id }}">
    {% csrf_token %}
        <fieldset>
            <input type="hidden" name="item_id" value="{{ item.id}}" />
            <input type="hidden" name="item_name" value="{{ item.product_title }}" />
            <input type="hidden" name="item_description" value="{{ item.product_related_name.first.product_description }}" />
            <input type="hidden" name="item_image" value="{{ item.product_image_front }}" />
            {% if item.product_discounted_price != null %}
                <input type="hidden" name="amount" value="{{ item.product_discounted_price }}" />
             {% else %}
                <input type="hidden" name="amount" value="{{ item.product_price }}" />
            {% endif %}
            <input type="hidden" name="item_quantity" value="1" />
            <input type="submit" name="submit" value="Add to cart" class="button" />
        </fieldset>
    </form>
</div>

auto/templates/coming-soon.html
{% load static %}
<html lang="zxx">
<head>
<title>Autolux</title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files -->
<link href="//fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Niconne" rel="stylesheet">
<!-- /font files -->
<!-- css files -->
{#<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />#}
<link href="{% static 'css/coming_soon.css' %} " rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/coming_soon_font-awesome.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- /css files -->
<body>
	<div class="w3l-banner-layer">
	<div class="container coming-soon-settings">
        <div class="row">
            <div class="col-md-12" align="center">
                <img class="coming-soon-img" src="{% static 'images/main_logo.png' %}">
                <h1 class="coming-soon-title">Unique Accessories For Your Car</h1>

                <div class="stay-tuned">
                    <h2 class="txt-w3_agile">stay tuned <br>we're launching soon. </h2>
                    <span class="bar"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12" align="center">
                <div class="agile_social_banner">
                    <ul class="social_list">
                        <li><a href="https://www.facebook.com/autolux.pk/" class="social_facebook"><span class="fa fa-facebook" aria-hidden="true"></span></a></li>
                        <li><a href="https://www.instagram.com/autolux.pk/" class="social_instagram"><span class="fa fa-instagram" aria-hidden="true"></span></a></li>
                        <li><a href="https://wa.me/923018430678" class="social_whatsapp">
                            <i class="fa fa-whatsapp"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

	</div>
	</div>
</body>
</html>

auto/templates/footer.html
{% load static %}
<footer>
    <!--/grids-->
<div class="coupons">
		<div class="coupons-grids text-center">
			<div class="w3layouts_mail_grid">
				<div class="col-md-3 w3layouts_mail_grid_left">
					<div class="w3layouts_mail_grid_left1 hvr-radial-out">
						<i class="fa fa-truck" aria-hidden="true"></i>
					</div>
					<div class="w3layouts_mail_grid_left2">
						<h3>FREE SHIPPING</h3>
						<p>We provide nation-wide free shipping facility</p>
					</div>
				</div>
				<div class="col-md-3 w3layouts_mail_grid_left">
					<div class="w3layouts_mail_grid_left1 hvr-radial-out">
						<i class="fa fa-headphones" aria-hidden="true"></i>
					</div>
					<div class="w3layouts_mail_grid_left2">
						<h3>Help-line</h3>
						<p>Active help-line from 10am – 7pm</p>
					</div>
				</div>
				<div class="col-md-3 w3layouts_mail_grid_left">
					<div class="w3layouts_mail_grid_left1 hvr-radial-out">
						<i class="fa fa-shopping-bag" aria-hidden="true"></i>
					</div>
					<div class="w3layouts_mail_grid_left2">
						<h3>Warranty</h3>
						<p> We provide 7-Days money-back guarantee for your convenience</p>
					</div>
				</div>
					<div class="col-md-3 w3layouts_mail_grid_left">
					<div class="w3layouts_mail_grid_left1 hvr-radial-out">
						<i class="fa fa-gift" aria-hidden="true"></i>
					</div>
					<div class="w3layouts_mail_grid_left2">
						<h3>Cash on Delivery</h3>
						<p>This service is available for your convenience</p>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
</div>
<!--grids-->
<!-- footer -->
<div class="footer">
	<div class="footer_agile_inner_info_w3l">
		<div class="col-md-4 footer-left">
            <h2><a href="{% url 'index' %}"><img src="{% static 'images/300x165.png' %}" alt=" " style="height: 5em;"> </a></h2>
			<p>AutoLux.pk is dedicated to provide unique and rare car accessories that are either
                not available in Pakistan or are extremely rare. We aim to import such automotive
                products and provide them at reasonable and competitive prices. All of our
                products and car accessories are self-imported by taking the market dynamics into
                account. However, we also arrange one-off shipments on pre-order for interested
                customers.
             </p>

            <a href="https://www.facebook.com/autolux.pk/" class="fa fa-facebook" data-toggle="modal"></a>
            <a href="https://www.instagram.com/autolux.pk/" class="fa fa-instagram" data-toggle="modal"></a>
            <a href="https://wa.me/923018430678" class="footer-whatsapp-fa fa-whatsapp footer-whatsapp-custom-class" data-toggle="modal"></a>

		</div>
		<div class="col-md-8 footer-right">
			<div class="sign-grds">
				<div class="col-md-4 col-md-offset-1 sign-gd">
					<h4>Our <span>Information</span> </h4>
					<ul>
						<li><a href="{% url 'index' %}">Home</a></li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
						<li><a href="{% url 'contact' %}">FAQs</a></li>
					</ul>
				</div>

				<div class="col-md-4 col-md-offset-1 sign-gd-two">
					<h4>Store <span>Information</span></h4>
					<div class="w3-address">
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-phone" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Phone Number</h6>
								<p>
                                    <a href="tel:+923018430678">+92 301 8430678</a>
                                </p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Email Address</h6>
								<p><a href="mailto:autoluxpk@gmail.com">autoluxpk@gmail.com</a></p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-map-marker" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Location</h6>
								<p>Lahore, Pakistan</p>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="clearfix"></div>
		<p class="copy-right">&copy 2018 AutoLux. All rights reserved </p>
	</div>
</div>
<!-- //footer -->
</footer>

auto/templates/place_order.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <title>Autolux Shipping Form</title>
  <!-- Meta-Tags -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="keywords" content="Autolux Shipping Form"/>

  <script>
    addEventListener("load", function () {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>
    {% block css %}
         <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'css/order_placing_style.css' %}" rel='stylesheet' type='text/css' />
        <link href="//fonts.googleapis.com/css?family=Abhaya+Libre:400,500,600,700,800" rel="stylesheet">
{#        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />#}
        <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
        <link href="{% static 'css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>

        <style>
            body {
                background: url("{{ orderBackgroundImage }}");
                background-position: center center;
                background-repeat:  no-repeat;
                background-attachment: fixed;
                background-size: cover;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                -ms-background-size: cover;
                font-family: 'Abhaya Libre', serif;
                text-align: center;
            }
            @media (max-width:500px){
                body {
                    background: url("{{ orderMobileBackgroundImage }}");
                    background-position: center center;
                    background-repeat:  no-repeat;
                    background-attachment: fixed;
                    background-size: cover;
                    -webkit-background-size: cover;
                    -moz-background-size: cover;
                    -o-background-size: cover;
                    -ms-background-size: cover;
                }
            }
        </style>
    {% endblock %}
  <!-- body -->
  <!--//fonts-->
</head>

<body>
{% block content %}
  <header>
    <h1>
        Autolux Shipping form
        <div align="center">
            <img src="{% static 'images/Auto Lux for about us.png' %}" alt=" " class="img-responsive" />
        </div>
    </h1>
  </header>
  <div class="w3ls-contact">
    <!-- form starts here -->
    <form action="#" method="post" id="submit_form">
        {% csrf_token %}
      <div class="agile-field-txt">
        <div class="mr_agilemain">
          <div class="left-wthree">
              <label class="bot_w3">
              {{ orderForm.first_name.label }}</label>
              {{ orderForm.first_name }}
          </div>
          <div class="left-wthree">
              <label class="bot_w3">
              {{ orderForm.last_name.label }}</label>
              {{ orderForm.last_name }}
          </div>
        </div>
      </div>
      <div class="agile-field-txt">
        <label>
          {{ orderForm.contact_number.label }}</label>
          {{ orderForm.contact_number }}
      </div>
      <div class="agile-field-txt">
        <label>
          {{ orderForm.email.label }}</label>
          {{ orderForm.email }}
      </div>
      <div class="agile-field-txt">
        <label>
          {{ orderForm.address.label }}</label>
          {{ orderForm.address }}
      </div>
        <div id="form_errors" class="alert alert-danger" style="display: none; width: 100%">
        </div>
      <div class="w3ls-contact  w3l-sub">

        <input type="submit" value="Place Order" id="place-order-btn">

      </div>
    </form>

  </div>
  <!-- //form ends here -->

    <div class="modal fade" id="thanksModal" tabindex="-1" role="dialog">
			<div class="modal-dialog custom-modal">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
						<div class="modal-body modal-body-sub_agile">

                            <h2>Thank you</h2>
                            <p>Your order Number is: <b id="order_number"></b></p>
                            <button class="checkout-delivery" onclick="location.href='{% url 'index' %}'">Shop More</button>

					</div>
				</div>
				<!-- //Modal content-->
			</div>
	</div>
     <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script>

        var cart = {};
        cart.products = [];
        if(!localStorage.getItem('cart')){
            window.localStorage.setItem('cart', JSON.stringify(cart));
        }

    </script>
    <script>


        $('#submit_form').on('submit', function(event){
            event.preventDefault();
            cart_info = localStorage.cart;
            $('#place-order-btn').attr("disabled", true);

            $.ajax({
                type: "POST",
                url: '{% url 'place_order' %}',
                data: {
                    first_name: $("#id_first_name").val(),
                    last_name: $("#id_last_name").val(),
                    email: $("#id_email").val(),
                    contact_number: $("#id_contact_number").val(),
                    address: $("#id_address").val(),
                    cart_info: cart_info,
                    payment_method: '{{payment_method}}',
                    token: '{{token}}',
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success:function(result) {
                    if(result.success) {
                        $('#order_number').html(result.orderNumber)
                        $('#thanksModal').modal('toggle');
                        $('#form_errors').hide();
                        var cart = {};
                        cart.products = [];
                        window.localStorage.clear();
                        window.localStorage.setItem('cart', JSON.stringify(cart));
                        $('#place-order-btn').removeAttr("disabled");
                    } else {
                        if(result.errors && result.errors.contact_number) {
                            $('#form_errors').text(result.errors.contact_number.toString());
                            $('#form_errors').show();
                        } else {
                            $('#form_errors').text(result.errors);
                            $('#form_errors').show();
                        }
                        $('#place-order-btn').removeAttr("disabled");
                    }
                    $('#place-order-btn').removeAttr("disabled");
                },
                error:function(result) {
                    console.log(result);
                    alert('error');
                    $('#place-order-btn').removeAttr("disabled");
                }
            });
        });
    </script>

{% endblock %}
</body>
<!-- //Body -->

</html>

auto/templates/verifyforzoho.html
1537976358446